---

- name: Install and Start nginx
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start nginx
      service:
         name: nginx
         state: started
    - name: Deploy Nginx
      copy:
        src: /home/ubuntu/ansible/index.html
        dest: /var/www/html/index.html
      become: true
      become_user: root
      become_method: sudo
